### ISSUE TITLE
Likes / Dislikes

### ISSUE THREAD

**Issue by ardalis** [ardalis/RegExLib.com#34]
Rather than ratings, Expressions should have likes or dislikes, which can be added by any registered user.

Each Like or Dislike should be its own record in the database and should include the date and user.

Since a user can't both Like and Dislike something, we should implement both as a single Reaction that a user can express. Something like:

```csharp
public class Reaction : BaseEntity
{
  public int ExpressionId {get; private set;}
  public string Reaction {get; private set; } // could be an enum; limit to Like and Dislike for now
  public DateTimeUtc DateLastUpdated { get; private set; } = DateTime.UtcNow;
}
```

**Comment by antmdvs** [comment]
@ardalis #ddd

I’m already struggling a bit with the domain model. If we were doing DDD and aggregates, would we have the below at this juncture? If we delete a User, would that cascade to their reactions? If so I suppose User would be the root? Or would Reaction belong in the Author-Expression aggregate since certainly deleting an Expression would cascade to its Reactions since a reaction can’t exist without an Expression? I don’t think that makes sense either because Author isn’t necessary to participate in data changes WRT reactions. In terms of transactional consistency I would think the boundary would be User-Expression-Reaction. 🧐🤔

(I also put ReactionType there, thinking an enum is effectively a VO..?)

![image](https://user-images.githubusercontent.com/17127310/86389391-3b8bf180-bc64-11ea-8b9d-30aad61d39c3.jpeg)

**Comment by ardalis** [comment]
It does get interesting quickly even for this simple site, eh? I don't have time to write more now but I'll revisit later.

**Comment by antmdvs** [comment]
Indeed it does :)

**Comment by ardalis** [comment]
Probably should create a new (open) issue to discuss this. My first thought is that Reactions are pretty much their own thing. You could have Reactions to anything. You just need some key for the "thing" and another key for the user and then either separate lists for Like or Dislike or just some kind of reaction type.

My next consideration is how will they be used? Do you show reactions on the user's home page? Maybe, but that's probably not their primary use. The primary use case is to show a count of reactions on a given resource. Think about reactions in Slack or Discord or even GitHub. You can add a reaction to this particular comment on this issue. The primary use case is "GetReactionsForResource(resourceKey)" which if there are several kinds of reactions does a group and count.

If I delete the resource, what should happen to its reactions? Either they're orphaned or they disappear with it.
If I delete the user/author, same question. And probably same answer.

In neither case must it happen immediately as part of the transaction though. We can allow for eventual consistency, assuming we're not enforcing foreign keys at the data layer.

Looking at GitHub as an example, they show a count of reactions but also will show who reacted when you mouse over, so they're fetching more than just the counts. It's also worth noting that their key is probably the username, not userid, which is nice because that's what they display on mouseover (instead of an int or guid key that would be useless or would require a call to translate to a username). This too argues for Reactions to be part of the Expression aggregate. So that's probably what I would do. Expression as aggregate root, Reaction as part of the aggregate. Navigation property from Expression to List<Reaction>. Key-only properties on Reaction to ExpressionId and Username.
