### ISSUE TITLE
API: List Expressions - Paginated

### ISSUE THREAD

**Issue by ardalis** [ardalis/RegExLib.com#9]
GET /api/expressions?page=0

Returns a result set that includes the total records, the current page, and an array of expressions. Page size can be fixed at 25.

This endpoint does not require authentication.

**Comment by ShadyNagy** [comment]
We need to update ardalis.ApiEndpoints to version 1.0.0 and use it in RegExLib.Infrastructure?
or we only need to add this to EfRepository?

```csharp
        public Task<List<T>> ListAsync<T>(int page) where T : BaseEntity
        {
            return _dbContext.Set<T>().Skip(perPage * (page - 1)).Take(perPage).ToListAsync();
        }
```

**Comment by ardalis** [comment]
The latter. Endpoints should only be referenced by asp.net core projects.

**Comment by antmdvs** [comment]
@ardalis Just to make sure I'm clear from a DDD, perspective, if we said the [the aggregate root is Author](https://github.com/ardalis/RegExLib.com/pull/14#discussion_r447150017), it's ok to directly query the Expressions table because "_aggregates and aggregates roots only apply to objects, not data?_" ([quoting Julie from the PS course](https://app.pluralsight.com/player?course=domain-driven-design-fundamentals&author=steve-smith&name=domain-driven-design-fundamentals-m4&clip=4&mode=live&start=71.61348900000004)).

**Comment by ardalis** [comment]
For read-only things, sure. For instance Author-Expression could be an aggregate, but that doesn't mean we can have a search expressions function that hits the expression database table directly and returns a read model (and maybe never looks at any of our entities).

Aggregates and Entities and indeed the whole domain model are primarily useful for business logic which almost always means some kind of write operation (or at least a command or action or some sort). Pure read operations, like searches and reporting, generally shouldn't use the domain model (or if they do, they should stop as soon as it causes pain, in favor of a separate read model).

**Comment by antmdvs** [comment]
Thanks @ardalis . Makes sense, assuming you meant "...but that doesn't mean we **can't** have a search expressions function...", not "can", right?

> Aggregates and Entities and indeed the whole domain model are primarily useful for business logic which almost always means some kind of write operation

Great insight! Got some good takeaways from this response. Thanks

**Comment by ardalis** [comment]
yes, **can't**. Sorry about that. :)
